"""Compare accessible data range: independent box-LHS vs manifold-anchored sampling.

Two views, both with REAL numbers:
  (1) knob space -- the actual pilot LHS draws (data/expanded_pilot/manifest.json) vs anchored
      draws generated by the proposed sampler. No simulation needed.
  (2) matching space -- design-optics BMAG at PENT (defaults.yml, the design-consistent
      lattice the curve was solved on) evaluated identically for both samplers' FF draws.
      This is the fair, cheap (no tracking) objective-space comparison of FF-matching coverage.

The anchored FF sampler: draw a target beta* (log-uniform over the feasible range), interpolate
the matched beta->FF-quad curve (from the 2026-06-19 PENT matching solve), add bounded per-quad
jitter, clip to EPICS bounds. Movers: narrowed box about their golden tuned values.

Figures -> lab-notebook/images/2026-06-21_manifold_coverage_{knobs,bmag}.png

Usage: PYTHONPATH=$PWD/src MPLBACKEND=Agg python -m twobunch_s2e_rl.analysis.manifold_coverage \
         [--n 400] [--jitter 0.06] [--no-tao]
"""
import argparse
import json

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from ..datagen.paths import repo_root, facet2_root

FIGDIR = "/home/rwu4/photoinjector-rl/lab-notebook/images"
FF = ["Q5FFkG", "Q4FFkG", "Q3FFkG", "Q2FFkG", "Q1FFkG", "Q0FFkG"]
GOLDEN_FF = np.array([-71.837, -81.251, 99.225, 126.350, -235.218, 126.353])
EPICS = np.array([(-256., 0.), (-446., 0.), (0., 457.), (0., 167.), (-257., 0.), (0., 167.)])

# Matched beta* -> FF-quad curve, feasible rows of results_beta_sweep.csv (2026-06-19 solve).
# columns: beta_m, Q5, Q4, Q3, Q2, Q1, Q0   (kG.m)
CURVE = np.array([
    [0.5000, -72.043, -81.473, 99.353, 126.438, -234.626, 126.394],
    [0.4372, -72.548, -84.684, 98.248, 128.526, -235.795, 128.541],
    [0.3824, -72.617, -88.209, 96.284, 131.302, -236.795, 129.195],
    [0.3344, -73.238, -91.585, 94.812, 133.249, -237.694, 130.892],
    [0.2924, -74.075, -94.885, 93.177, 135.074, -238.483, 132.472],
    [0.2557, -76.494, -95.835, 90.898, 136.372, -239.123, 134.560],
    [0.2236, -78.094, -98.558, 88.777, 138.022, -239.714, 135.803],
    [0.1955, -79.715, -102.185, 87.256, 139.390, -240.266, 137.271],
    [0.1710, -82.150, -105.568, 86.237, 140.262, -240.761, 139.312],
    [0.1495, -84.528, -109.354, 84.770, 141.457, -241.165, 140.485],
    [0.1308, -87.490, -113.457, 83.789, 142.471, -241.442, 141.461],
    [0.1144, -90.856, -117.965, 83.020, 143.416, -241.677, 142.339],
    [0.1000, -94.770, -122.902, 82.551, 144.313, -241.826, 142.947],
    [0.0874, -98.923, -128.129, 81.850, 145.250, -242.014, 143.539],
    [0.0765, -103.287, -133.581, 81.146, 146.161, -242.185, 144.003],
])
BETA_ASC = CURVE[::-1, 0]            # ascending beta for np.interp
QUAD_ASC = CURVE[::-1, 1:]
BETA_LO, BETA_HI = CURVE[-1, 0], CURVE[0, 0]   # 0.0765 .. 0.5 m
EXCURSION = np.abs(GOLDEN_FF - CURVE[-1, 1:])  # golden -> floor span per quad (kG.m)

MOVERS = ["S1EL_xOffset", "S1EL_yOffset", "S2EL_xOffset", "S2EL_yOffset",
          "S2ER_xOffset", "S2ER_yOffset", "S1ER_xOffset", "S1ER_yOffset"]
GOLDEN_MOV = np.array([0.0009068268, 0.0001315754, -0.000388583, 0.0001165775,
                       -0.0001679111, -0.0014881668, 0.0013323302, -0.0011182646])
MOVER_NARROW = 0.15e-3   # +/- about golden, m


def sample_anchored_ff(rng, n, jitter_frac):
    """Anchored FF draws: beta* log-uniform -> interp matched curve -> + jitter -> clip."""
    beta = np.exp(rng.uniform(np.log(BETA_LO), np.log(BETA_HI), n))
    ff = np.column_stack([np.interp(beta, BETA_ASC, QUAD_ASC[:, j]) for j in range(6)])
    ff = ff + rng.normal(0, 1, ff.shape) * (jitter_frac * EXCURSION)
    ff = np.clip(ff, EPICS[:, 0], EPICS[:, 1])
    return beta, ff


def bmag(beta, alpha, beta0=0.5):
    """Mismatch vs golden (beta0=0.5 m, alpha0=0)."""
    return beta / beta0 * 0.5 + 0.5 * beta0 * (1 + alpha**2) / beta


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n", type=int, default=400)
    ap.add_argument("--jitter", type=float, default=0.06)
    ap.add_argument("--no-tao", action="store_true")
    args = ap.parse_args()
    rng = np.random.default_rng(0)

    # --- load the real pilot LHS draws -------------------------------------------------
    man = json.load(open(repo_root() / "data" / "expanded_pilot" / "manifest.json"))
    rows = [m for m in man if not m["is_baseline_repeat"]]
    lhs_ff = np.array([[m["knobs"][k] for k in FF] for m in rows])
    lhs_mov = np.array([[m["knobs"][k] for k in MOVERS] for m in rows])
    n = min(args.n, len(rows))
    lhs_ff, lhs_mov = lhs_ff[:n], lhs_mov[:n]

    beta_anc, anc_ff = sample_anchored_ff(rng, n, args.jitter)
    anc_mov = GOLDEN_MOV + rng.uniform(-MOVER_NARROW, MOVER_NARROW, (n, 8))

    # --- FIG 1: knob-space coverage ----------------------------------------------------
    fig, ax = plt.subplots(1, 3, figsize=(17, 5.2))
    # (a) Q4FF vs Q0FF, (b) Q1FF vs Q5FF  -- with matched curve + golden
    for a, (i, j) in zip(ax[:2], [(1, 5), (4, 0)]):
        a.scatter(lhs_ff[:, i], lhs_ff[:, j], s=9, alpha=0.4, color="#4c72b0", label="box-LHS")
        sc = a.scatter(anc_ff[:, i], anc_ff[:, j], s=12, alpha=0.7,
                       c=beta_anc * 100, cmap="autumn", label="anchored")
        a.plot(QUAD_ASC[:, i], QUAD_ASC[:, j], "k-", lw=1.5, label="matched curve")
        a.scatter([GOLDEN_FF[i]], [GOLDEN_FF[j]], marker="*", s=240, color="lime",
                  edgecolor="k", zorder=5, label="golden")
        a.set_xlabel(f"{FF[i]} [kG·m]"); a.set_ylabel(f"{FF[j]} [kG·m]")
        a.legend(fontsize=8)
    cb = fig.colorbar(sc, ax=ax[1]); cb.set_label("anchored target β* [cm]", fontsize=8)
    # (c) movers
    ax[2].scatter(lhs_mov[:, 0] * 1e3, lhs_mov[:, 6] * 1e3, s=9, alpha=0.4,
                  color="#4c72b0", label="box-LHS (±1.5 mm)")
    ax[2].scatter(anc_mov[:, 0] * 1e3, anc_mov[:, 6] * 1e3, s=12, alpha=0.7,
                  color="#dd8452", label="anchored (±0.15 mm)")
    ax[2].scatter([GOLDEN_MOV[0] * 1e3], [GOLDEN_MOV[6] * 1e3], marker="*", s=240,
                  color="lime", edgecolor="k", zorder=5, label="golden")
    ax[2].set_xlabel("S1EL_xOffset [mm]"); ax[2].set_ylabel("S1ER_xOffset [mm]")
    ax[2].legend(fontsize=8)
    fig.suptitle("Accessible knob-space region: independent box-LHS vs manifold-anchored "
                 f"(n={n})", fontsize=13)
    fig.tight_layout()
    p1 = f"{FIGDIR}/2026-06-21_manifold_coverage_knobs.png"
    fig.savefig(p1, dpi=130); plt.close(fig)
    print("wrote", p1)

    # --- FIG 2: matching-space coverage (design-optics BMAG at PENT) --------------------
    if args.no_tao:
        print("skipping Tao BMAG figure (--no-tao)")
        return
    import FACET2_S2E as qs
    root = str(facet2_root())
    tao = qs.initializeTao(filePath=root, runSetLatticeTF=True, runImpactTF=False)

    def design_bmag_max(ff_rows):
        out = []
        for r in ff_rows:
            tao.cmd("set global lattice_calc_on = F")
            for k, v in zip(FF, r):
                qs.setQuadkG(tao, k[:-2], float(v))
            tao.cmd("set global lattice_calc_on = T")
            t = tao.twiss_at_s(ele="PENT", s_offset=0.0)
            out.append(max(bmag(t["beta_a"], t["alpha_a"]), bmag(t["beta_b"], t["alpha_b"])))
        return np.array(out)

    print(f"evaluating design BMAG for {n} LHS + {n} anchored FF draws...")
    lhs_b = design_bmag_max(lhs_ff)
    anc_b = design_bmag_max(anc_ff)

    fig, ax = plt.subplots(figsize=(8.5, 5.5))
    lo = min(lhs_b.min(), anc_b.min()); hi = max(lhs_b.max(), anc_b.max())
    bins = np.logspace(np.log10(max(lo, 0.5)), np.log10(hi), 50)
    ax.hist(lhs_b, bins=bins, alpha=0.6, color="#4c72b0",
            label=f"box-LHS (median {np.median(lhs_b):.1f})")
    ax.hist(anc_b, bins=bins, alpha=0.7, color="#dd8452",
            label=f"anchored, jitter={args.jitter:g} (median {np.median(anc_b):.2f})")
    ax.axvline(1.0, color="k", ls=":", lw=1, label="matched (BMAG=1)")
    ax.axvline(1.5, color="green", ls="--", lw=1, label="BMAG=1.5")
    ax.set_xscale("log"); ax.set_xlabel("design-optics BMAG_max at PENT (defaults.yml)")
    ax.set_ylabel("count"); ax.legend(fontsize=9)
    ax.set_title(f"Accessible matching range: FF box-LHS vs anchored (n={n} each)")
    fig.tight_layout()
    p2 = f"{FIGDIR}/2026-06-21_manifold_coverage_bmag.png"
    fig.savefig(p2, dpi=130); plt.close(fig)
    print("wrote", p2)
    print(f"\nBMAG_max  box-LHS:   median {np.median(lhs_b):.1f}  p5-p95 "
          f"{np.percentile(lhs_b,5):.1f}-{np.percentile(lhs_b,95):.0f}")
    print(f"BMAG_max  anchored:  median {np.median(anc_b):.2f}  p5-p95 "
          f"{np.percentile(anc_b,5):.2f}-{np.percentile(anc_b,95):.2f}  "
          f"frac<1.5: {np.mean(anc_b<1.5):.0%}  frac<2: {np.mean(anc_b<2):.0%}")


if __name__ == "__main__":
    main()
